
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Users/cheta/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/mnt/c/Users/cheta/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/mnt/c/Extra/Tesseract OCR/ImageMagick-7.1.2-Q16-HDRI/"
      - "/mnt/c/Users/cheta/AppData/Local/Programs/Python/Python312/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/msys64/ucrt64/bin/"
      - "/mnt/c/Extra/Node JS/Original/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Program Files/clarinet/bin/"
      - "/mnt/c/msys64/mingw64/bin/"
      - "/mnt/c/Users/cheta/AppData/Local/Programs/Tesseract-OCR/"
      - "/mnt/c/Extra/Tesseract OCR/gs10.06.0/bin/"
      - "/mnt/c/Program Files/PostgreSQL/18/bin/"
      - "/mnt/c/Program Files/Cloudflare/Cloudflare WARP/"
      - "/mnt/c/Program Files/k6/"
      - "/mnt/c/Program Files/Memurai/"
      - "/mnt/c/Program Files/Amazon/AWSCLIV2/"
      - "/mnt/c/Program Files/PuTTY/"
      - "/mnt/c/Users/admin/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Program Files/LLVM/bin/"
      - "/mnt/c/wsl-aliases/"
      - "/mnt/c/Extra/terraform_1.15.2_windows_amd64/"
      - "/mnt/c/Program Files/Go/bin/"
      - "/mnt/c/Program Files/CMake/bin/"
      - "/mnt/c/Users/cheta/AppData/Local/Programs/Python/Python312/Scripts/"
      - "/mnt/c/Users/cheta/scoop/shims/"
      - "/mnt/c/Users/cheta/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Users/cheta/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "/mnt/c/Users/cheta/AppData/Roaming/npm/"
      - "/mnt/c/Extra/Git/Git/cmd/"
      - "/mnt/c/Users/cheta/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/"
      - "/mnt/c/Users/cheta/AppData/Local/Programs/Windsurf/bin/"
      - "/mnt/c/Users/cheta/go/bin/"
      - "/snap/bin/"
    searched_directories:
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Users/cheta/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/mnt/c/Users/cheta/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/mnt/c/Extra/Tesseract OCR/ImageMagick-7.1.2-Q16-HDRI"
        - "/mnt/c/Users/cheta/AppData/Local/Programs/Python/Python312/"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/msys64/ucrt64/bin"
        - "/mnt/c/Extra/Node JS/Original/"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Program Files/clarinet/bin/"
        - "/mnt/c/msys64/mingw64/bin"
        - "/mnt/c/Users/cheta/AppData/Local/Programs/Tesseract-OCR"
        - "/mnt/c/Extra/Tesseract OCR/gs10.06.0/bin"
        - "/mnt/c/Program Files/PostgreSQL/18/bin"
        - "/mnt/c/Program Files/Cloudflare/Cloudflare WARP/"
        - "/mnt/c/Program Files/k6/"
        - "/mnt/c/Program Files/Memurai/"
        - "/mnt/c/Program Files/Amazon/AWSCLIV2/"
        - "/mnt/c/Program Files/PuTTY/"
        - "/mnt/c/Users/admin/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Program Files/LLVM/bin"
        - "/mnt/c/wsl-aliases"
        - "/mnt/c/Extra/terraform_1.15.2_windows_amd64"
        - "/mnt/c/Program Files/Go/bin"
        - "/mnt/c/Program Files/CMake/bin"
        - "/mnt/c/Users/cheta/AppData/Local/Programs/Python/Python312/Scripts/"
        - "/mnt/c/Users/cheta/AppData/Local/Programs/Python/Python312/"
        - "/mnt/c/Users/cheta/scoop/shims"
        - "/mnt/c/Users/cheta/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Users/cheta/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Users/cheta/AppData/Roaming/npm"
        - "/mnt/c/Extra/Git/Git/cmd"
        - "/mnt/c/Users/cheta/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin"
        - "/mnt/c/Users/cheta/AppData/Local/Programs/Windsurf/bin"
        - "/mnt/c/Users/cheta/go/bin"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
...
